### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by gasperr** [fhirbase/fhirbase-plv8#103]
I am getting the error below when trying to call any function from pgadmin. Any idea why?

ERROR:  ReferenceError: require is not defined
DETAIL:  fhir_read_resource() LINE 2:   var mod = require("/fhirbase/src/fhir/crud.coffee")
*********\* Error **********

**Comment by niquola** [comment]
https://github.com/fhirbase/fhirbase-plv8/blob/master/README.md#postgresql-config-for-plv8 u have to set plv8 init function on fresh connection (or this could be done in postgresql config)
