### ISSUE TITLE
Unable to create custom search parameter on an element in resourceType = Patient

### ISSUE THREAD

**Issue by VarunOjha** [fhirbase/fhirbase-plv8#118]
I've been playing around with FHIRbase2 for sometime. I wish to have some elements in my resource, other than the ones defined in the StructureDefination. I also want to run search(fhir_search), on the custom parameters I added. I tried to go about this, by first adding a new SearchParameter by using fhir_create_resource, in which I defined the x path for the element I wish to query on. Further, I also added the field in the StructureDefination of the Patient. 
I still get the error that the MetaIndex was not found. I am assuming the MetaIndex are created during the time of DB creation in Postgres using plv8. 

Is there a way to add custom search parameter for elements that you can define on a resource ?
Also,
How does FHIRbase attempts to prevent duplicate insertion of patients within the table ?
Please help or let me know if this customization is even possible or not.

**Comment by niquola** [comment]
Fhirbase should work with custom searchparameters. Please provide your example, so we can understand what's going wrong.

Fhirbase does not handle duplicates, it's up to your application. In fhirbase you can create resource with id and it will throw exception (I hope - if not - we have to fix it) if same id is already occupied. So one possible trick is to generate id by hashing combination of identifying elements on your side.

**Comment by VarunOjha** [comment]
My Example -
I am trying to store information for patients in the patients table. However, I am also trying to store other elements (panNo, passportNo etc, common in india) with the patient information, other than the ones in StructureDefinition. So with other elements like name, gender, address, I also store these fields in the json. Now, when I attempt to do a fhir_search({"resource":"Patient", "queryString":"panNO=34bnwe"}), it didn't work. I created a new search parameter panNo using fhir_create_resource, it says the 

> PostgreSQL said: Error: MetaIndex: Element [["Patient","panNO"]] -> Patient.panNo not found !

So, I added panNO, in the elements part of the StructureDefinition json. Still getting the same error as above. 

**{
        "max": "*",
        "min": 0,
        "path": "Patient.panNo",
        "type": [
          {
            "code": "string"
          }
        ],
        "short": "Tax Information for the patient",**

The problem I am trying to solve is add more fields in the patients documents, and query w.r.t those fields. What should be the ideal way to implement this ?

**Comment by niquola** [comment]
First of all panNo and passport number could live in standard Patient.identifier element. And Please, show me the whole searchparameter resource.

**Comment by VarunOjha** [comment]
This is the searchParameter source I used. 
{
  "resource": {
    "base": "Patient",
    "code": "panNo",
    "date": "2016-03-15T04:30:42+00:00",
    "name": "panNo",
    "type": "string",
    "xpath": "f:Patient/f:panNo",
    "contact": [
      {
        "telecom": [
          {
            "value": "http://hl7.org/fhir",
            "system": "other"
          }
        ]
      },
      {
        "telecom": [
          {
            "value": "http://www.hl7.org/Special/committees/pafm/index.cfm",
            "system": "other"
          }
        ]
      }
    ],
    "extension": [
      {
        "valueString": "Patient.panNo"
      }
    ],
    "publisher": "Custom",
    "xpathUsage": "normal",
    "description": "panNo for the patient",
    "resourceType": "SearchParameter"
  }
}

Please let me know what's failing here.

**Comment by vadi2** [comment]
Wouldn't it be more correct to store these as extensions?

**Comment by VarunOjha** [comment]
@vadi2  - Please explain in detail!

**Comment by niquola** [comment]
Yes, it should be extension if not in FHIR! But in @VarunOjha  case standard element Patient.identifier is best match :)

**Comment by vadi2** [comment]
@VarunOjha use the existing Patient.identifier in your case for storage,
but in future, don't add new elements to the data model just like this -
use the extension element (see extensibility.html).

**Comment by VarunOjha** [comment]
@niquola @vadi2  Patient.identifier covers most of my use cases for now. Thanks
