### ISSUE TITLE
GET is recognized as invalid operation in transaction

### ISSUE THREAD

**Issue by draakhan** [fhirbase/fhirbase-plv8#125]
Hi!

Tested on v1.3.0.21.

```
SELECT fhir_truncate_storage('{"resourceType": "Patient"}');

SELECT fhir_create_resource('{"allowId": true, "resource": {"resourceType": "Patient","name": [{"given": ["Tim"]}], "id": "2345"}}');

select fhir_transaction('{"resourceType":"Bundle","type":"transaction","entry":[{"request":{"method":"GET","url":"Patient/2345"}}]}');
```

the output of the transaction is:

```
{"resourceType":"OperationOutcome","issue":[{"severity":"error","code":"422","diagnostics":"Invalid operation GET Patient/2345"}]}
```

**Comment by danil** [comment]
@draakhan, i can not reproduce
https://github.com/fhirbase/fhirbase-plv8/blob/ae45083cdbdce6a83c9473abc58b2c05f16f72a3/test/integration/issues/125_get_is_recognized_as_invalid_operation_in_transaction_spec.coffee#L29
May be problem with your local installation?
Please, try drop/crate bd and reinstall fhirbase from scratch

**Comment by bartlomiejs-kainos** [comment]
Reinstalled from scratch using v1.3.0.22 and now it works.
