### ISSUE TITLE
fhire base functions not working

### ISSUE THREAD

**Issue by orbitboy007** [fhirbase/fhirbase-plv8#157]
ERROR:  function fhir_create_storage(unknown) does not exist
LINE 1: SELECT fhir_create_storage('{"resourceType": "Patient"}');
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

how i can solve it?

**Comment by niquola** [comment]
Execute this on a fresh connection `SET plv8.start_proc = 'plv8_init';`
