### ISSUE TITLE
Incorrect search behavior 

### ISSUE THREAD

**Issue by ratp0is0n** [fhirbase/fhirbase-plv8#162]
The following query doesn't work because the second patient guid starts with 'eb' and it is a registered prefix (operator) in [FHIR:](https://www.hl7.org/fhir/search.html#prefix)

```
SELECT fhir_search_sql('{"resourceType": "Provenance", 
"queryString": "patient=235d1b44-23dc-4d17-9df8-819851886322,eb4648e5-62a5-4513-ab39-02d9b610f700"}');
```

**Comment by maksym** [comment]
Provenance.patient search parameter has reference type so try to use something like patient=Patient/id
