### ISSUE TITLE
fhir_search Device with querystring does not give result

### ISSUE THREAD

**Issue by Ronm10** [fhirbase/fhirbase-plv8#170]
Hi,

I am new on FHIRBASE, just installed  docker for windows with the latest image.

I need to store and query devices, when I create the entry below and query the resource using the query below I do not get a result. If I search without the querystring I do get my line as a result.

Also when I do the fhir_read with the ID, I do get a result but I think it is malformed.  It gives fieldnames before the resourcetype.

I use pgadmin to do the query.

Can anyone help me on this?
thanks
Ron

SELECT fhir_update_resource('{"resource": {"resourceType": "Device","id": "QA0001", "identifier": "QA0001", "location": "HOME", "udiCarrier": "QA00012014", "status": "Active" }}');

SELECT fhir_search('{"resourceType": "Device", "queryString": "identifier=QA0001"}');

Result:
{"resourceType":"Bundle","link":[{"url":"/Device?identifier=QA0001&_page=0","relation":"self"}],"total":0,"type":"searchset","entry":[]}

SELECT fhir_read_resource('{"resourceType": "Device", "id": "QA0001"}');

result:

{"status":"Active","udiCarrier":"QA00012014","resourceType":"Device","meta":{"versionId":"b0935204-0ffc-45e7-a762-80cb965059ed","lastUpdated":"2016-12-29T18:03:38.793Z","extension":[{"url":"fhir-request-method","valueString":"POST"},{"url":"fhir-request-uri","valueUri":"Device"}]},"location":"HOME","identifier":"QA0001","id":"QA0001"}

**Comment by niquola** [comment]
Hi, your Resource is probably invalid - identifier is complex type in FHIR - https://www.hl7.org/FHIR/datatypes.html#identifier. If you just need to search by id - use `_id=v1,v2` search

**Comment by Ronm10** [comment]
Hi,

Ggot my search by identifier also working. have to create the identifier with a value property
"identifier": [{"value": ["QA0001"]}]  then I can search with identifier =...   also the search with _id works. 

Thanks
