### ISSUE TITLE
Test indexing performance

### ISSUE THREAD

**Issue by niquola** [fhirbase/fhirbase-plv8#20]
See https://github.com/fhirbase/fhirbase/issues/77

**Comment by niquola** [comment]
https://github.com/fhirbase/fhirbase/issues/75

**Comment by danil** [comment]
@niquola commented on Oct 30, 2015

> See fhirbase/fhirbase#77
> fhirbase/fhirbase#75

`fhir_extract_as_token` and `fhir_extract_as_daterange` was tested and looks ok
https://github.com/fhirbase/fhirbase-plv8/blob/v1.3.0.7/src/benchmark.coffee#L122
https://github.com/fhirbase/fhirbase-plv8/blob/v1.3.0.7/src/benchmark.coffee#L162
http://fhirbase.github.io/docs.html#performance
