### ISSUE TITLE
Production Stability?

### ISSUE THREAD

**Issue by vlall** [fhirbase/fhirbase-plv8#4]
Hi, i'm wondering how stable this new version is for implementing on a production environment if I instead point it to a MySQL database. Any information would be greatly appreciated.

**Comment by niquola** [comment]
This version is under active development. We are going stabilize it in couple of month for production grade. It would not work with MySQL, because it uses a lot of advanced PostgreSQL features: plv8, jsonb, GIN & GIST

**Comment by vlall** [comment]
Thanks for the quick answer! Although those specific features for PostgreSQL prompted you guys to adopt it, are there any other general reasons why you guys chose PostgreSQL?

**Comment by niquola** [comment]
This is "holy war" question :)

At least the list of features above is evidence.

They are incomparable:
MySQL is hipster database for quick web development, where PostgreSQL is robust & featured database, same class as MSSQL.

google for comparison articles :)
