### ISSUE TITLE
travis: build for different versions of plv8

### ISSUE THREAD

**Issue by niquola** [fhirbase/fhirbase-plv8#47]

**Comment by ir4y** [comment]
I offer to implement this task in next steps:
1. Create docker images for actual versions of postgresql and plv8.
   We can use https://github.com/clkao/docker-postgres-plv8/blob/master/9.4-1.4/Dockerfile as an example.
2. Update .travis.yml to run tests in next way.
   Create SQL setup script
   launch docker container for postgres-plv8 version 1.4.3
   Setup fhirbase to fhirbase
   launch tests
   launch docker container for other postgres-plv8 version , etc

What do you think ?

**Comment by niquola** [comment]
Does travis allow to run docker?

**Comment by ir4y** [comment]
I have used this hack https://github.com/moul/travis-docker , but i think that native docker support appears  for travis https://docs.travis-ci.com/user/docker/

**Comment by ir4y** [comment]
I have confirmed that travis-ci supports docker.
I have test it at https://github.com/Brogency/balancer project. I had some troubles with docker-compose but i hope i will fix it.

So we can reuse this knowledge for fhirbase

**Comment by danil** [comment]
fixed https://github.com/fhirbase/fhirbase-plv8/blob/da8c5c93faaf2506240dee372ed8e7f76ee9add7/.travis.yml#L34
if not, feel free to reopen
