### ISSUE TITLE
fhir_update_resource validation errors

### ISSUE THREAD

**Issue by szymonp-kainos** [fhirbase/fhirbase-plv8#49]
There are some validation issues with `fhir_update_resource` function
1. update resource with non existing id and meta - fails
2. update resource with non existing id - not fails, creates resource
3. update resource without id in resource doesn't fail

**Comment by niquola** [comment]
2) should work this way

**Comment by szymonp-kainos** [comment]
Well http://hl7.org/fhir/http.html#update states: `If no id element is provided, or the value is wrong, the server SHALL respond with a HTTP 400 error code, and SHOULD provide an operation outcome identifying the issue.`. So, shouldn't it fail with 400 ?

**Comment by niquola** [comment]
> Note that servers MAY choose to allow clients to PUT a resource to a location that does not yet exist on the server - effectively, allowing the client to define the id of the resource. Whether a server allows this is a deployment choice based on the nature of its relationships with the clients. While many servers will not allow clients to define their ids, there are several reasons why it may be necessary in some configurations:

http://hl7-fhir.github.io/http.html#update

**Comment by niquola** [comment]
I just do not understand, what means `wrong`? :)

**Comment by szymonp-kainos** [comment]
Damn FHIR.
Ok, let's leave it that way.
