### ISSUE TITLE
Structure definition for MedicationOrder wrong medication reference definition

### ISSUE THREAD

**Issue by szymonp-kainos** [fhirbase/fhirbase-plv8#52]
Structure definition indicates that there is 
`MedicationOrder.medication[x]`
but there is no way to relate it to fields like `medicationReference` and requests cannot be validated.
Used example from FHIR documentation http://hl7.org/fhir/medicationorderexample1.json.html where there is field `medicationReference`, cannot be validated with structure definition from fhirbase - no field relation, as cannot get field by path from structure definition.

**Comment by niquola** [comment]
Please clarify problem. Do you mean, FHIR metadata in fhirbase is out of date?

**Comment by szymonp-kainos** [comment]
Structure definitions from fhirbase cannot be used to validate incoming json resource (or any other).
For example, fhirbase in structure definition for `MedicationOrder` contains field `medication[x]` and there is no way to relate that field to `medicationReference` from incoming FHIR json resource for `MedicationOrder` (how `medication[x]` relates to either `medicationReference` or `medicationCodeableConcept` ?). I think all resources with `[x]` in FHIR documentation will have same issue with structure definition from fhirbase.

**Comment by niquola** [comment]
I'm still out of understanding: StructureDefinition from fhirbase is the same as from FHIR official distribution.
So your idea is that official StructureDefinition could not be used for resource validation?

**Comment by szymonp-kainos** [comment]
Sorry about that. This issue can be closed.
Structure definition has really changed and after migration our validation stopped working. After investigation we changed our validation and treat `[x]` from name as wildcard.
