### ISSUE TITLE
VRead validation error

### ISSUE THREAD

**Issue by szymonp-kainos** [fhirbase/fhirbase-plv8#53]
There is validation code in `fhir_vread_resource`

```
exports.fhir_vread_resource = (plv8, query)->
  assert(query.id, 'query.id')
  version_id = query.versionId || query.meta.versionId
  assert(version_id, 'query.versionId or query.meta.versionId')
  assert(query.resourceType, 'query.resourceType')
```

checking if there is `id` in query, but instead it should be checking `versionId` (first assert)

**Comment by niquola** [comment]
Please clarify the problem.
Both ids are required, because there is no unique constraint on versionId by themself, just for pair id & versionId.

**Comment by szymonp-kainos** [comment]
In documentation of usage there is line

``` sql
SELECT fhir_vread_resource('{"resourceType": "Patient", "versionId": "????"}');
```

and there is no `id` in example.
Also isn't `versionId` supposed to be unique ?

**Comment by szymonp-kainos** [comment]
Also previous version didn't take id, only versionId

**Comment by niquola** [comment]
VersionId in fhirbase is now unique because of it is uuid and handled by fhirbase itself. So if you think, this is critical - we could use only versionId for vread operation.

**Comment by szymonp-kainos** [comment]
It's not critical and both can be used, but usage example in project readme is misleading. Maybe just change that ?

**Comment by niquola** [comment]
I think it's better to do less assumptions, so implementation could be changed later. Gonna change Readme ;)
