### ISSUE TITLE
Search with date gt and lt isn't working

### ISSUE THREAD

**Issue by szymonp-kainos** [fhirbase/fhirbase-plv8#54]
`gt` and `lt` params for search aren't working correctly, e.g.

``` sql
SELECT fhir_search('{"resourceType": "Patient", "queryString": "birthdate=gt2000-02-02"}');
```

returns

``` json
 "{"resourceType":"Bundle","type":"searchset","total":3,"link":[{"relation":"self","url":"Patient/birthdate=gt2000-02-02&page=1"}],"entry":[{"resource":{"id":"34fd0835-3e77-45c1-bd0d-6826ed023284","meta":{"versionId":"a8d9f39b-171d-4812-b433-66724ce303bc","lastUpdated":"2015-12-11T13:51:57.550Z"},"name":[{"text":"John Doe"}],"birthDate":"2000-02-02","resourceType":"Patient"}},{"resource":{"id":"aa24c9b3-93fc-45c9-aac5-1dacb954d631","meta":{"versionId":"319fd73e-481e-4e66-b876-75743e963560","lastUpdated":"2015-12-11T13:51:57.979Z"},"name":[{"text":"John Doe"}],"birthDate":"2000-02-03","resourceType":"Patient"}},{"resource":{"id":"2124e2f8-6022-4317-aadd-bfe341aa5030","meta":{"versionId":"3dcc9a77-4eb1-4c90-8680-5020a75dafec","lastUpdated":"2015-12-11T13:58:13.714Z"},"name":[{"text":"John Doe"}],"birthDate":"2000-02-02","resourceType":"Patient"}}]}"
```

3 results where only 1 is correct

**Comment by niquola** [comment]
Here is logic behind dates:

if fhirbase get date - it indexes it as a range `[<date>T00:00:00, <date>T23:59:59]`, which sounds quite logical. When you are looking by date, fhirbase builds query for range intersection with `[<date>T00:00:00, infinity]`. That's why this behavior. If you think it should be different - please argument.

**Comment by szymonp-kainos** [comment]
Well in that case shouldn't `gt` take bigger (after) than `<date>T23:59:59` and `le` smaller (before) than `date>T00:00:00` dates ? That would make most sense for date to be 'outside' of range.

**Comment by niquola** [comment]
Sounds reasonable, let's do it
