### ISSUE TITLE
Create isn't failing when id is provided 

### ISSUE THREAD

**Issue by szymonp-kainos** [fhirbase/fhirbase-plv8#58]
Query:

``` sql
SELECT fhir_create_resource('{"resource": {"resourceType": "Patient", "id": "thh","name": [{"given": ["Smith"]}]}}');
```

creates resource and set id to given in resource, but in FHIR documentation http://hl7.org/fhir/http.html#create it states:

```
The request body SHALL be a FHIR Resource without an id element (this is the only case where a resource exists without an id element). If an ID element is provided, the server SHALL respond with a HTTP 400 error code, and SHOULD provide an operation outcome identifying the issue.
```

**Comment by niquola** [comment]
Yes, we did it a little bit against specification intentionally - we want create by create :).
If this is confusing - let's discuss.

**Comment by szymonp-kainos** [comment]
Well, it's confusing, when you can create resource with id using create and update methods. I would go with what FHIR specifies and go with creating with id by update/put and knowing that create/post method will generate id and won't allow when usage when there is one.

**Comment by niquola** [comment]
Ok, let's follow standard

**Comment by niquola** [comment]
I'm going to add option to fhir_resource_create:

``` sql
SELECT fhir_create_resource('{"allowId": true, "resource",{"id": "newid"}}');
```
