### ISSUE TITLE
Add docker support

### ISSUE THREAD

**Issue by ir4y** [fhirbase/fhirbase-plv8#60]
I think that docker container should only provide an enviroment to build SQL setup script and run tests.
This docker image will not provide fhirbase as a service.
It will be need to get image of postgres-plv8 (see #47) and run SQL script manualy to setup fhirbase.

**Comment by niquola** [comment]
I think, for test and quick start purposes we could also create image with everything inside.

**Comment by ir4y** [comment]
Yes, this image will be use release version of SQL setup scritp from here https://github.com/fhirbase/fhirbase-plv8/releases.

I think it should be a separated repo.

**Comment by danil** [comment]
@ir4y please try this dockerfile https://github.com/fhirbase/fhirbase-plv8/blob/master/Dockerfile.
This dockerfile compiles `plv8` from source as well as runs tests

**Comment by ir4y** [comment]
@danil thank you! It's a great work!

But in my opinion it's not a good parctice to mix different parts of application in one  container (postgres, nodejs builder, etc..) And run tests in process of container build.

I think is should be separate container for posrgresql which support `plv8`
Separate container for nodejs fhirbase app to build an sql initila script.
I have already started implementation of them 
https://github.com/ir4y/fhirbase-plv8/blob/master/docker-compose.yml
https://github.com/ir4y/fhirbase-plv8/blob/master/Dockerfile
https://github.com/ir4y/fhirbase-plv8/blob/master/docker_init.sh

But i have been stucked with my current work routine. =(

I will continue my work on fhirebase after hollidays. I have a lot of ideas and plans ;)

**Comment by danil** [comment]
`Dockerfile-dev` now install pg and compiles plv8 and does not run test explicitly
https://github.com/fhirbase/fhirbase-plv8/blob/af1a7fe3cb46a0c1f4e2ef7c05826af981419f39/Dockerfile-dev
if not enough, feel free to reopen
