### ISSUE TITLE
Read and Vread operation outcome for missed read is malformed

### ISSUE THREAD

**Issue by Andrzej-Pietrzak** [fhirbase/fhirbase-plv8#62]
On v0.0.1-beta.4
Two issues: 
1. When reading resource that does not exist the message is not tokenized with the id:
"{"resourceType":"OperationOutcome","issue":[{"severity":"error","code":"not-found","details":{"coding":[{"code":"MSG_NO_EXIST","display":"Resource Id \"%s\" does not exist"}]},"diagnostics":"Resource Id \"ishop\" does not exist"}]}"
Notice the \"%s\" part
1. When Vreading the message is not tokenized with id, and it would be best if it also contained an versionId segment

**Comment by danil** [comment]
@Andrzej-Pietrzak 

> On v0.0.1-beta.4
> Two issues: 
> 1. When reading resource that does not exist the message is not tokenized

fixed in master

> When Vreading the message is not tokenized with id, and it would be best if it also contained an versionId segment

`versionId` added to `OperationOutcome.issue[0].diagnostics`

**Comment by danil** [comment]
@Andrzej-Pietrzak feel free to reopen issue
