### ISSUE TITLE
feature: fhir_truncate_storage

### ISSUE THREAD

**Issue by niquola** [fhirbase/fhirbase-plv8#64]
return number of removed resources

**Comment by niquola** [comment]
And return OperationOutcome, i.e. valid FHIR resource

**Comment by niquola** [comment]
If table does not exist, return OperationOutcome

**Comment by danil** [comment]
@niquola 

> return number of removed resources

What's done: returning OperationOutcome on successful and on erroneous truncation.
What's not done: returning number of removed resources because postgres not returns this number.
