### ISSUE TITLE
Deleted version and Vread of deleted version

### ISSUE THREAD

**Issue by Andrzej-Pietrzak** [fhirbase/fhirbase-plv8#65]
On v0.0.1-beta.5

As this might seem obscure the fhir spec suggests that deletion creates an empty entry in the history, just a mark a deletion happened.

From: http://www.hl7.org/implement/standards/fhir/http.html#delete
" For servers that maintain a version history, the delete interaction does not remove a resource's version history. From a version history respect, deleting a resource is the equivalent of creating a special kind of history entry that has no content and is marked as deleted. "

Also: Vreading that particular version should return a message instead of the resource

From: http://www.hl7.org/implement/standards/fhir/http.html#vread
" If the version referred to is actually one where the resource was deleted, the server should return a 410 status code. "

What do you think about adding a status code for that situation instead of a entity ?

**Comment by danil** [comment]
hi, please try `v0.0.1-beta.7`

@Andrzej-Pietrzak

> As this might seem obscure the fhir spec suggests that deletion
> creates an empty entry in the history, just a mark a deletion
> happened.

For this purposes we use meta extensions `fhir-request-method` and
`fhir-request-uri`. For example this patient version created on
delete.

``` json
{
  "meta": {
    "extension": [
      {
        "url": "fhir-request-method",
        "valueString": "DELETE"
      }, {
        "url": "fhir-request-uri",
        "valueUri": "Patient"
      }
    ]
  },
  "resourceType": "Patient",
  "id": "example",
  "name": [{"given": ["John"]}]
}
```

In future we will recommend FHIR community add meta extensions
`fhir-request-method` and `fhir-request-uri` as standard.

> Also: Vreading that particular version should return a message
> instead of the resource
> 
> What do you think about adding a status code for that situation
> instead of a entity?

Ok. Vread of the deleted version now returns OperationOutcome.
Relying on this OperationOutcome's `coding` server can return the
appropriate http status code.

``` json
{
  "resourceType": "OperationOutcome",
  "issue": [
    {
      "severity": "error",
      "code": "not-found",
      "details": {
        "coding": [
          {
            "code": "MSG_DELETED_ID",
            "display": "The resource \"someId\" has been deleted"
          }
        ]
      },
      "diagnostics": "Resource Id \"someId\" with versionId \"someVersionId\" has been deleted"
    }
  ]
}
```

**Comment by Andrzej-Pietrzak** [comment]
The meta extensions looks promising and works well when tested, on the other hand since there is no support for that in tools we use (e.g HAPI parser) we're unable to use this beta or any further ones that have this change.

The vread of deleted looks great, could we add a similar code to the read-deleted ?

**Comment by danil** [comment]
@Andrzej-Pietrzak

> The meta extensions looks promising and works well when tested, on
> the other hand since there is no support for that in tools we use
> (e.g HAPI parser) we're unable to use this beta or any further ones
> that have this change.

i changed the extension on an empty resource (as described
http://www.hl7.org/implement/standards/fhir/http.html#delete),
please try v0.0.1-beta.9

> The vread of deleted looks great, could we add a similar code to the
> read-deleted ?

done

**Comment by Andrzej-Pietrzak** [comment]
When there's no marker like the 'request' node for each entry in the body, like these guys did:

http://fhir2.healthintersections.com.au/open/Patient/1/_history?_format=json

It might be the best to leave at least the meta+id, the empty resource looks a bit like a server error, and its not quite clear what was the deleted versionId ;)

**Comment by danil** [comment]
@Andrzej-Pietrzak

> http://fhir2.healthintersections.com.au/open/Patient/1/_history?_format=json

Hi, i'm a little confused.

Unfortunately "history bundle" example that you provide do not contain
"deleted" resource.

> It might be the best to leave at least the meta+id, the empty resource
> looks a bit like a server error, and its not quite clear what was the
> deleted versionId ;)

Please provide an example of "history bundle" which shows a
"deleted" resource.

**Comment by Andrzej-Pietrzak** [comment]
Ah sorry, my mistake. This one should do:
http://fhir2.healthintersections.com.au/open/Patient/1234567915/_history?_format=json

**Comment by Andrzej-Pietrzak** [comment]
Plus there's a bug on that server - when you 'undelete' it doesn't retrieve  the deleted version from the history or removes it

**Comment by izi** [comment]
The issue on our side is that non of the tools that we are using support the extension in meta tag. Modification does not fix anything on our side as we are not able to use this element.

```
"meta": {
  "extension": [
    {
      "url": "fhir-request-method",
      "valueString": "POST"
    },
    {
      "url": "fhir-request-uri",
      "valueUri": "Patient"
    }
  ],
  "versionId": "59ecf732-d46e-42d6-ae3d-53fd19ec6d7f",
  "lastUpdated": "2016-01-20T21:38:53.996Z"
}
```

Is it possible to disable returning of the extension in the meta element?

**Comment by niquola** [comment]
Do you use HAPI? 

We've discussed it whit FHIR skype, formally it's ok to have extension in meta:

>  @Nicola Meta is an Element, which has extensions, so I would say yes.

**Comment by izi** [comment]
Yes, we are using HAPI for validation and few other use cases. It's not treating meta as element that can be extended and it does not allow to skip this rule. They have some possible configurations around error handling but treat this case strictly.

**Comment by niquola** [comment]
> James Agnew: @Niquola- Sure, that'd be great. Agree we should support that.

**Comment by izi** [comment]
Thanks Niquola for clarifying that. We have implemented a temporary workaround for this issue.

**Comment by danil** [comment]
@izi 

> Thanks Niquola for clarifying that. We have implemented a temporary workaround for this issue.

i treat this issue as closed
