### ISSUE TITLE
Search by boolean token

### ISSUE THREAD

**Issue by Andrzej-Pietrzak** [fhirbase/fhirbase-plv8#67]
Its possibile to retrieve records matching only the 'true' value on a token/boolean search as in Patient.active:

-- test for boolean token search
SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"MarvinColeman","name":[{"use":"official","given":["Marvin"],"family":["Coleman"]}],"active":true,"resourceType":"Patient"}}');
SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"MattHays","name":[{"use":"official","given":["Matt"],"family":["Hays"]}],"active":"true","resourceType":"Patient"}}');
SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"CathrineWillows","name":[{"use":"official","given":["Cathrine"],"family":["Willows"]}],"active":false,"resourceType":"Patient"}}');
SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"CynthiaHughs","name":[{"use":"official","given":["Cynthia"],"family":["Hughs"]}],"resourceType":"Patient"}}');

-- basic boolean token searches:
SELECT fhir_search('{"resourceType": "Patient", "queryString": "active=true"}'); -- ok
SELECT fhir_search('{"resourceType": "Patient", "queryString": "active:missing=true"}'); -- nok, CathrineWillows (active=false) is included
SELECT fhir_search('{"resourceType": "Patient", "queryString": "active:missing=false"}'); -- nok, CathrineWillows (active=false) not included
SELECT fhir_search('{"resourceType": "Patient", "queryString": "active=false"}'); -- nok, CathrineWillows (active=false) not included

**Comment by mlapshin** [comment]
please check release 0.0.1-beta.14
