### ISSUE TITLE
String search accent and case sensitivity

### ISSUE THREAD

**Issue by Andrzej-Pietrzak** [fhirbase/fhirbase-plv8#68]
On beta5:
1. The fhir spec suggests that the default search behavior is a 'starts with' and results are accent and case insensitive
Right now the case insensitivity seems to be applied only in certain cases, and not in others 
2. The exact keyword does not change the accent sensitivity nor case sensitivity

Samples:
SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"id3","name":[{"use":"nickname","given":["Kaśka"]},{"use":"official","given":["Katarzyna"],"family":["Kowalska"]}],"resourceType":"Patient"}}');
SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"id4","name":[{"use":"official","given":["洋"],"family":["刘"]},{"use":"official","given":["Yáng"],"family":["刘"]},{"use":"nickname","given":["健康"]}],"resourceType":"Patient"}}');
SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"id7","name":[{"use":"official","given":["Адам"]},{"use":"official","given":["Adam"]}],"resourceType":"Patient"}}');

SELECT fhir_search('{"resourceType": "Patient", "queryString": "given=Kaska"}'); -- no results 
SELECT fhir_search('{"resourceType": "Patient", "queryString": "given=Kaśka"}'); -- ok, 1 res
SELECT fhir_search('{"resourceType": "Patient", "queryString": "given=Yáng"}');  -- no results ?
SELECT fhir_search('{"resourceType": "Patient", "queryString": "given=Yang"}');  -- ok, 1 result
SELECT fhir_search('{"resourceType": "Patient", "queryString": "given=Адам"}');  -- no results ?

SELECT fhir_search('{"resourceType": "Patient", "queryString": "given:exact=Kaska"}'); -- ok, 0 res
SELECT fhir_search('{"resourceType": "Patient", "queryString": "given:exact=Kaśka"}'); -- ok, 1 res
SELECT fhir_search('{"resourceType": "Patient", "queryString": "given:exact=Yáng"}'); -- no results ?
SELECT fhir_search('{"resourceType": "Patient", "queryString": "given:exact=Yang"}'); -- resutls present ?
SELECT fhir_search('{"resourceType": "Patient", "queryString": "given:exact=Ада"}'); -- ok, no res
SELECT fhir_search('{"resourceType": "Patient", "queryString": "given:exact=Адам"}'); -- no results ?

SELECT fhir_search('{"resourceType": "Patient", "queryString": "given:contains=Yang"}'); -- ok, 1 res
SELECT fhir_search('{"resourceType": "Patient", "queryString": "given:contains=Yáng"}'); -- no results ?
SELECT fhir_search('{"resourceType": "Patient", "queryString": "given:contains=ang"}'); -- ok, 1 res
SELECT fhir_search('{"resourceType": "Patient", "queryString": "given:contains=Ада"}'); -- no results ?
SELECT fhir_search('{"resourceType": "Patient", "queryString": "given:contains=Адам"}'); -- no results ?
SELECT fhir_search('{"resourceType": "Patient", "queryString": "given:contains=да"}'); -- ok, 1 res

**Comment by mlapshin** [comment]
please check release 0.0.1-beta.14
