### ISSUE TITLE
Assert the 'queryString' param is defined and not empty on search 

### ISSUE THREAD

**Issue by Andrzej-Pietrzak** [fhirbase/fhirbase-plv8#69]
On beta5
The fhir_search function will return everything of a given resource if the 'queryString' is not provided or given empty. 
What do you think about this ?

**Comment by niquola** [comment]
I think, it's expected behavior :)

See Grahame server: 

```
http://fhir2.healthintersections.com.au/open/Patient/_search?_format=json&given=
```
