### ISSUE TITLE
Certain date formats saved cause search errors

### ISSUE THREAD

**Issue by Andrzej-Pietrzak** [fhirbase/fhirbase-plv8#72]
If any resource has a dateTime field with a value given as iso date with timezone e.g:

SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"id5","deceasedDateTime":"1980-09-10T11:15:52+02:00","active":true,"resourceType":"Patient"}}');

Its not possible to run any search for that date parameter due to scrip error:
SELECT fhir_search('{"resourceType": "Patient", "queryString": "deathdate=eq1980-09-10"}');
SELECT fhir_search('{"resourceType": "Patient", "queryString": "deathdate=eq1972"}');
SELECT fhir_search('{"resourceType": "Patient", "queryString": "deathdate=gt2000"}');

all result in:
ERROR:  Error: Error: date.to_range: Don't know how to handle 1980-09-10T11:15:52+02:00
DETAIL:  plv8_init() LINE 139:     return plv8.execute.call(plv8, q[0], q.slice(1));

**Comment by danil** [comment]
@Andrzej-Pietrzak please check 0.0.1-beta.15
