### ISSUE TITLE
Date search with 'gt' comparison returns equal dates

### ISSUE THREAD

**Issue by Andrzej-Pietrzak** [fhirbase/fhirbase-plv8#73]
For samples:
 fhir_create_resource('{"allowId": true, "resource": {"id":"id1","birthDate":"1971-04-20","active":true,"resourceType":"Patient"}}');
SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"id2","birthDate":"1973-05-31","active":true,"resourceType":"Patient"}}');
SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"id3","birthDate":"1973-05-31","active":true,"resourceType":"Patient"}}');
SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"id4","birthDate":"1978-05-31","active":true,"resourceType":"Patient"}}');
SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"id5","active":true,"resourceType":"Patient"}}');

Searching for: 
SELECT fhir_search('{"resourceType": "Patient", "queryString": "birthdate=gt1978-05-31"}'); 
Returns the equal date, same as the 'ge' comparison would.
It seems inconsistent with 'lt', which does not return the 'equality' match.
e.g.
SELECT fhir_search('{"resourceType": "Patient", "queryString": "birthdate=lt1971-04-20"}'); -- ok, 0 res

Similar thing to:
https://github.com/fhirbase/fhirbase-plv8/issues/54

**Comment by mlapshin** [comment]
fixed in 0.0.1-beta.12
