### ISSUE TITLE
fhir_create_storage fails on keywords.

### ISSUE THREAD

**Issue by izi** [fhirbase/fhirbase-plv8#77]
It seems that you cannot create FHIR resources which are named like keywords in SQL:
- Group
- Order
- Binary

You can create all other storages.

**Comment by danil** [comment]
@izi

> It seems that you cannot create FHIR resources which are named like
> keywords in SQL:
> 
> Group
> Order
> Binary

from now `fhir_create_resource` should work
https://github.com/fhirbase/fhirbase-plv8/blob/v0.0.1-beta.13/test/core/schema_spec.coffee#L24
