### ISSUE TITLE
Paging in search is broken

### ISSUE THREAD

**Issue by Andrzej-Pietrzak** [fhirbase/fhirbase-plv8#78]
On beta5
1. Links.url's for a page are malformed: 
    e.g. "url": "Patient/gender=male&_count=0&page=1"
2. Pages/Count is not applied on the result set -> always all results
3. Since its not applied then corner cases in page/count params are not handled either (e.g. page=1, page=asdf, page=-1, count=0, count=-1, count=max_int+1) 

Samples:

SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"id1","gender":"male","active":true,"resourceType":"Patient"}}');
SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"id2","gender":"male","active":true,"resourceType":"Patient"}}');
SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"id3","gender":"male","active":true,"resourceType":"Patient"}}');
SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"id4","gender":"female","active":true,"resourceType":"Patient"}}');
SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"id5","active":true,"resourceType":"Patient"}}');

SELECT fhir_search('{"resourceType": "Patient", "queryString": "gender=male"}'); -- ok, 3 res
SELECT fhir_search('{"resourceType": "Patient", "queryString": "gender=male&_count=0"}'); -- nok, 3 results, expected 0 or error

SELECT fhir_search('{"resourceType": "Patient", "queryString": "gender=male&_count=1&_page=1"}'); -- nok, 3 res, expected 1
SELECT fhir_search('{"resourceType": "Patient", "queryString": "gender=male&_count=1&_page=2"}'); -- nok, 3 res, expected 1
SELECT fhir_search('{"resourceType": "Patient", "queryString": "gender=male&_count=1&_page=3"}'); -- nok, 3 res, expected 1, link to the 4'th page visible

SELECT fhir_search('{"resourceType": "Patient", "queryString": "gender=male&_count=2&_page=1"}'); -- nok, 3 res, expected 2
SELECT fhir_search('{"resourceType": "Patient", "queryString": "gender=male&_count=2&_page=2"}'); -- nok, 3 res, expected 1, link to the 3'rd page visible
SELECT fhir_search('{"resourceType": "Patient", "queryString": "gender=male&_count=2&_page=3"}'); -- expected last page (1 result) or error
SELECT fhir_search('{"resourceType": "Patient", "queryString": "gender=male&_count=10&_page=0"}'); -- expected 0 results or error
SELECT fhir_search('{"resourceType": "Patient", "queryString": "gender=male&_count=asdf&_page=asdf"}'); -- expected errors

**Comment by mlapshin** [comment]
fixed in 0.0.1-beta.12
