### ISSUE TITLE
Install scripts contains absolute paths

### ISSUE THREAD

**Issue by Andrzej-Pietrzak** [fhirbase/fhirbase-plv8#79]
What is the point in splitting the install scripts for the demo into two files in the beta release ?
Should I run both?
It might be good to update the installation instructions then

Secondly - the install scripts contain absolute paths:
e.g 
/home/danil/src/vendor/waveaccess/fhirbase-plv8/src
Is this like expected or handled any way?

Thirdly: 
waveaccess ? :)

**Comment by danil** [comment]
@Andrzej-Pietrzak 

> Secondly - the install scripts contain absolute paths:
> e.g 
> /home/danil/src/vendor/waveaccess/fhirbase-plv8/src
> Is this like expected or handled any way?

about the "absolute path") is not the path, this is the "identifier" of the module

**Comment by danil** [comment]
Hi

@Andrzej-Pietrzak

> What is the point in splitting the install scripts for the demo into
> two files in the beta release?

SQL script without "path" suffix (for example
`fhirbase-0.0.1-beta.7.sql`) will install firebase from scratch.

Script with "path" suffix will upgrade existing fhirbase.
For example `fhirbase-0.0.1-beta.7-patch.sql` will upgrade fhirbase
from version `0.0.1-beta.6` to version `0.0.1-beta.7`.

So if you whant upgrade then you should use file with suffix "path".
If installing from scratch you should use file without suffix "path".

Both options are tested
https://github.com/fhirbase/fhirbase-plv8/blob/v0.0.1-beta.7/release.sh#L26.

> Should I run both?

No.

> It might be good to update the installation instructions then

I added instructions into readme file
https://github.com/fhirbase/fhirbase-plv8/tree/3de959d84659781144cc615011475188cd40658a#upgrade

> Secondly - the install scripts contain absolute paths:
> e.g
> /home/danil/src/vendor/waveaccess/fhirbase-plv8/src
> Is this like expected or handled any way?

Yes, expected. This just "cosmetic issue".

> Thirdly:
> waveaccess ? :)

Never mind)
