### ISSUE TITLE
Version information

### ISSUE THREAD

**Issue by agusenko** [fhirbase/fhirbase-plv8#83]
Version information should be stored in the database and query through the function

**Comment by danil** [comment]
@agusenko please try v0.0.1-beta.14

**Comment by danil** [comment]
resource `Conformance` now provide information about version
https://github.com/fhirbase/fhirbase-plv8/blob/v1.3.0.7/test/fhir/conformance_spec.coffee#L20
with respect to FHIR specification
http://hl7-fhir.github.io/conformance.html#resource
if not enough, feel free to reopen
