### ISSUE TITLE
Search bundle total count doesn't show entries added with _include or _revinclude

### ISSUE THREAD

**Issue by Andrzej-Pietrzak** [fhirbase/fhirbase-plv8#84]
Samples:

SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"prc1","goal":[{"reference":"Goal/goal.id1"},{"reference":"Goal/goal.id2"}],"status":"active","subject":{"reference":"Patient/patrickrobinson"},"resourceType":"CarePlan"}}');
SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"goal.id1","status":"in-progress","description":"goal1","resourceType":"Goal"}}');
SELECT fhir_create_resource('{"allowId": true, "resource": {"id":"goal.id2","status":"in-progress","description":"goal2","resourceType":"Goal"}}');

SELECT fhir_search('{"resourceType": "CarePlan", "queryString": "_id=prc1&_include=goal"}'); --ok, but the overall count in response meta is wrong

Notice in the results- "total": 1

**Comment by niquola** [comment]
Should it?

**Comment by Andrzej-Pietrzak** [comment]
It could

I asked the team and this is what I got for an answer: http://gifsec.com/wp-content/uploads/2014/03/NO-Gif.gif

Lets keep it as is, sorry for the trouble ;)
