### ISSUE TITLE
URLs in search results have a typo

### ISSUE THREAD

**Issue by Andrzej-Pietrzak** [fhirbase/fhirbase-plv8#85]
http://www.hl7.org/implement/standards/fhir/search.html#2.1.1.2

The Fhir search is either:
"GET [base]/[resourcetype]?name=value&..."
or
"POST  [base]/[type]/_search{?[parameters]{&_format=[mime-type]}}"

currently:
e.g.
"url": "CarePlan/search?_id=prc1&_include=goal&_page=0"

**Comment by danil** [comment]
fixed in v1.3.0.11 https://github.com/fhirbase/fhirbase-plv8/blob/v1.3.0.11/test/fhir/search/pagination_search.yaml#L59
if not, feel free to reopen
