### ISSUE TITLE
Search for audit event action does not work

### ISSUE THREAD

**Issue by Andrzej-Pietrzak** [fhirbase/fhirbase-plv8#87]
Search by action, AuditEvent.event.action, always returns 0 results

e.g
SELECT fhir_search('{"resourceType": "AuditEvent", "queryString": "action=C"}'); 
SELECT fhir_search('{"resourceType": "AuditEvent", "queryString": "action=c"}');

**Comment by danil** [comment]
I can not reproduce

@Andrzej-Pietrzak please see https://github.com/fhirbase/fhirbase-plv8/blob/f37f917555c6def0a861135e819fa49f6437a0d4/test/fhir/search_spec.coffee#L77

**Comment by szymonp-kainos** [comment]
It will fail (won't find it) if AuditEvent contains capital letter, e.g. `"action": "R"` or `"action": "RRr",`. If there are only small letters it works. In FHIR documentations action codes consist of single capital letter. Tested on beta 19.

**Comment by danil** [comment]
@Andrzej-Pietrzak, @szymonp-kainos please try v1.3.0.3

**Comment by danil** [comment]
consider it fixed (https://github.com/fhirbase/fhirbase-plv8/blob/0e9e5258dedb6b07cb8eb2e61f8eb213f9c9cc2d/test/fhir/search_spec.coffee#L77),
if not, feel free to reopen
