### ISSUE TITLE
Missing handling for transactions including searches.

### ISSUE THREAD

**Issue by izi** [fhirbase/fhirbase-plv8#89]
In the example transaction calls you can find something like:

```
{
    "resourceType": "Bundle",
    "id": "bundle-transaction",
    "type": "transaction",
    "entry": [{
        "request": {
            "method": "GET",
            "url": "/Patient?name=peter"
        }
    }]
}
```

Is this restriction by design? Fhirbase does not have handler for raw searches.

**Comment by danil** [comment]
@izi 

> Is this restriction by design? Fhirbase does not have handler for raw searches.

now have
https://github.com/fhirbase/fhirbase-plv8/blob/v1.3.0.8/test/fhir/transaction_spec.coffee#L53
if not, feel free to reopen
