### ISSUE TITLE
Transaction - referential integrity - server assigned ids

### ISSUE THREAD

**Issue by izi** [fhirbase/fhirbase-plv8#91]
Fhirbase should support

```
 ”urn:uuid:[uuid value]"
```

Notation allows to create a temporary ids which will be substituted during transaction execution.

Full example can be checked at:
http://jamesagnew.github.io/hapi-fhir/doc_rest_client_examples.html

**Comment by mlapshin** [comment]
Just commited a very naive implementation. You can find transaction example here: https://github.com/fhirbase/fhirbase-plv8/blob/master/test/fhir/fixtures/transaction_examples.yml#L139

NB Circular references still not supported.

**Comment by danil** [comment]
Hope this fixed (v1.3.0.15). If not, feel free to reopen.
