### ISSUE TITLE
Ошибка функции fhir.update 

### ISSUE THREAD

**Issue by agusenko** [fhirbase/fhirbase-plv8#93]
При отправке результатов исследования возникла ошибка FHIRbaseException: Call fhir.update FHIRbase function failed. Reason P0001: expected last versionId bd729b18-6382-4423-befd-fa37b026b4e6, but got b864ef7b-d727-4e44-8528-836b28f98512 Смотрела функцию crud.update, интересно про old_vid := _resource_#>>'{meta,versionId}'; - у меня есть текст запроса POST и там versionId нет вообще (в успешных запросах тоже нет), значит он обращается к базе и вытягивает оттуда content(jsonb) из нужного ресурса и засылает его в процедуру? Повторный запрос отработал корректно, и такая ситуация периодически повторяется, вот разбираемся...

**Comment by niquola** [comment]
Are you sure, that you are using fhirbase-plv8?

**Comment by agusenko** [comment]
No, we are use fhirbase ONE (https://github.com/fhirbase/fhirbase), but this branch is'n supported.

**Comment by niquola** [comment]
We strongly recommend you to switch to newer version ;)
