### ISSUE TITLE
Unsupported sorting of search results by date

### ISSUE THREAD

**Issue by szymonp-kainos** [fhirbase/fhirbase-plv8#94]
Executing query

``` sql
select fhir_search('{"resourceType": "Observation", "queryString": "patient=jayson&code=8310-5&_count=10&_sort:desc=date"}')
```

returns error

```
ERROR: Error: Unsupported search type [undefined]}
SQL state: XX000
Detail: plv8_init() LINE 2696:       throw new Error("Unsupported search type [" + searchType + "]}");
```

[Observation](https://www.hl7.org/fhir/observation.html) contains searching by date, so sorting should also be possible.

Tested on beta 18

**Comment by szymonp-kainos** [comment]
What's the status on this issue ?

**Comment by Andrzej-Pietrzak** [comment]
Rested on a forked 1.6 release:
This seems to be fixed, I'm not seeing any issues we've seen before. I believe that this can be closed
