### ISSUE TITLE
Search by lastUpdated not supported

### ISSUE THREAD

**Issue by danil** [fhirbase/fhirbase-plv8#97]
Search by `lastUpdated` raise error: `No parser for special - lastUpdated`.
https://github.com/fhirbase/fhirbase-plv8/blob/5e7cf0e51bb32edd241b0e196f285f943343b542/test/fhir/search_spec.coffee#L232

See documentation http://hl7-fhir.github.io/search.html#lastUpdated

**Comment by swiftcents** [comment]
Also, does not search for the  _lastUpdated
Error "No parser for special - lastUpdated"
How to obtain resources for which it is necessary to take into account the last modification date. Can we do it some other way, except for a request   search '{"resourceType":"Patient","queryString":"_lastUpdated=2016-03-08"}'

**Comment by niquola** [comment]
It's bug and should be fixed ;)

**Comment by danil** [comment]
@swiftcents please try `v1.3.0.4`
