### ISSUE TITLE
Release roadmap

### ISSUE THREAD

**Issue by vadi2** [fhirbase/fhirbase-plv8#99]
I see that all releases so far are pre-releases and latest one is a breaking one, which makes fhirbase a bit scary to adopt. When are stable releases expected?

**Comment by niquola** [comment]
We are going align to FHIR releases. I think, we have to follow  FHIR versioning. Last release was for FHIR 2.1. Breking changes in last release are not related to API (which is quite stable), but about changes in FHIR metadata. If you have ideas, how to create patches for such type of updates - you are welcome to discuss and contribute ;)

This is tricky problem.
I see the following strategy;
- Calculate diff between current and new metadata
- Generate patch to apply this diff
- if metadata was changed - raise conflict, which should be resolved manually
- provide helpers to migrate resources (data) to new version (semiautomatic)

Health Samurai can provide this service   ;)

**Comment by vadi2** [comment]
I see, thanks. I'm going to be using PostgreSQL and jsonb for my personal FHIR project and was thinking of adopting fhirbase as it builds on these technologies already.
